import React from 'react';
import {
  // 原有图标
  Code2, Cpu, Wifi, Zap, Gauge, Layers, Binary, Server, Network, Shield, Settings2, Terminal, Workflow, HardDrive, Radio, Check,
  // 工业/工控
  Factory, Cog, Wrench, GaugeCircle, Thermometer, Activity, Power, Plug, Cable, Router, Satellite, Antenna, RadioTower, Bluetooth, EthernetPort,
  // 数据/分析
  BarChart3, LineChart, PieChart, TrendingUp, TrendingDown, Database, Table, FileSpreadsheet, Filter, Search,
  // 安全/可靠
  Lock, Unlock, Key, Fingerprint, Scan, Eye, EyeOff, AlertTriangle, AlertCircle, Bell,
  // 时间/确定性
  Clock, Timer, Hourglass, Calendar, History, GitBranch, GitMerge, Link, Unlink, ArrowLeftRight,
  // 开发/代码
  FileCode, Braces, Brackets, Bug, TestTube, Package, Box, Container,
  // 通用/界面
  Home, User, Users, Mail, Phone, MapPin, Globe, Cloud, Download, Upload,
  // 硬件/设备
  Monitor, Tablet, Smartphone, Printer, Camera, Microchip, CircuitBoard, MemoryStick,
  // 扩充图标
  Sun, Zap as ZapIcon, Train, FlaskConical, Pencil, Settings, LifeBuoy, GraduationCap, Building2, Lightbulb, Award, Trophy, Target, Rocket, Handshake, Users2,
  // 方向/箭头
  ArrowRight, ChevronDown, ArrowLeft, ArrowUp, ArrowDown, ChevronRight, ChevronUp,
  // 新增
  Battery,
} from 'lucide-react';

export type IconName =
  // 原有
  | 'code'
  | 'cpu'
  | 'wifi'
  | 'zap'
  | 'gauge'
  | 'layers'
  | 'binary'
  | 'server'
  | 'network'
  | 'shield'
  | 'settings'
  | 'terminal'
  | 'workflow'
  | 'harddrive'
  | 'radio'
  | 'check'
  // 工业/工控
  | 'factory'
  | 'cog'
  | 'wrench'
  | 'gaugeCircle'
  | 'thermometer'
  | 'activity'
  | 'power'
  | 'plug'
  | 'cable'
  | 'router'
  | 'satellite'
  | 'antenna'
  | 'radioTower'
  | 'bluetooth'
  | 'ethernet'
  // 数据/分析
  | 'barChart'
  | 'lineChart'
  | 'pieChart'
  | 'trendingUp'
  | 'trendingDown'
  | 'database'
  | 'table'
  | 'spreadsheet'
  | 'filter'
  | 'search'
  // 安全/可靠
  | 'lock'
  | 'unlock'
  | 'key'
  | 'fingerprint'
  | 'scan'
  | 'eye'
  | 'eyeOff'
  | 'alertTriangle'
  | 'alertCircle'
  | 'bell'
  // 时间/确定性
  | 'clock'
  | 'timer'
  | 'hourglass'
  | 'calendar'
  | 'history'
  | 'gitBranch'
  | 'gitMerge'
  | 'link'
  | 'unlink'
  | 'arrowLeftRight'
  // 开发/代码
  | 'fileCode'
  | 'braces'
  | 'brackets'
  | 'bug'
  | 'testTube'
  | 'package'
  | 'box'
  | 'container'
  // 通用/界面
  | 'home'
  | 'user'
  | 'users'
  | 'mail'
  | 'phone'
  | 'mapPin'
  | 'globe'
  | 'cloud'
  | 'download'
  | 'upload'
  // 硬件/设备
  | 'monitor'
  | 'tablet'
  | 'smartphone'
  | 'printer'
  | 'camera'
  | 'microchip'
  | 'circuitBoard'
  | 'memoryStick'
  // 扩充图标
  | 'sun'
  | 'zapIcon'
  | 'train'
  | 'flask'
  | 'pencil'
  | 'settings2'
  | 'lifeBuoy'
  | 'graduationCap'
  | 'building2'
  | 'lightbulb'
  | 'award'
  | 'trophy'
  | 'target'
  | 'rocket'
  | 'handshake'
  | 'users2'
  // 方向/箭头
  | 'arrowRight'
  | 'chevronDown'
  | 'arrowLeft'
  | 'arrowUp'
  | 'arrowDown'
  | 'chevronRight'
  | 'chevronUp'
  // 新增
  | 'battery';

interface IconProps {
  name: IconName;
  className?: string;
}

const iconMap: Record<IconName, React.ComponentType<{ className?: string }>> = {
  // 原有
  code: Code2,
  cpu: Cpu,
  wifi: Wifi,
  zap: Zap,
  gauge: Gauge,
  layers: Layers,
  binary: Binary,
  server: Server,
  network: Network,
  shield: Shield,
  settings: Settings2,
  terminal: Terminal,
  workflow: Workflow,
  harddrive: HardDrive,
  radio: Radio,
  check: Check,
  // 工业/工控
  factory: Factory,
  cog: Cog,
  wrench: Wrench,
  gaugeCircle: GaugeCircle,
  thermometer: Thermometer,
  activity: Activity,
  power: Power,
  plug: Plug,
  cable: Cable,
  router: Router,
  satellite: Satellite,
  antenna: Antenna,
  radioTower: RadioTower,
  bluetooth: Bluetooth,
  ethernet: EthernetPort,
  // 数据/分析
  barChart: BarChart3,
  lineChart: LineChart,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  database: Database,
  table: Table,
  spreadsheet: FileSpreadsheet,
  filter: Filter,
  search: Search,
  // 安全/可靠
  lock: Lock,
  unlock: Unlock,
  key: Key,
  fingerprint: Fingerprint,
  scan: Scan,
  eye: Eye,
  eyeOff: EyeOff,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  bell: Bell,
  // 时间/确定性
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  calendar: Calendar,
  history: History,
  gitBranch: GitBranch,
  gitMerge: GitMerge,
  link: Link,
  unlink: Unlink,
  arrowLeftRight: ArrowLeftRight,
  // 开发/代码
  fileCode: FileCode,
  braces: Braces,
  brackets: Brackets,
  bug: Bug,
  testTube: TestTube,
  package: Package,
  box: Box,
  container: Container,
  // 通用/界面
  home: Home,
  user: User,
  users: Users,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  globe: Globe,
  cloud: Cloud,
  download: Download,
  upload: Upload,
  // 硬件/设备
  monitor: Monitor,
  tablet: Tablet,
  smartphone: Smartphone,
  printer: Printer,
  camera: Camera,
  microchip: Microchip,
  circuitBoard: CircuitBoard,
  memoryStick: MemoryStick,
  // 扩充图标
  sun: Sun,
  zapIcon: ZapIcon,
  train: Train,
flask: FlaskConical,
    pencil: Pencil,
    settings2: Settings,
    lifeBuoy: LifeBuoy,
  graduationCap: GraduationCap,
  building2: Building2,
  lightbulb: Lightbulb,
  award: Award,
  trophy: Trophy,
  target: Target,
  rocket: Rocket,
  handshake: Handshake,
  users2: Users2,
  // 方向/箭头
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  // 新增
  battery: Battery,
};

export function Icon({ name, className = "w-7 h-7" }: IconProps) {
  const IconComponent = iconMap[name];
  return <IconComponent className={className} />;
}